### ISSUE TITLE
Suggestions to subtitles in [Kaleido-SCY] Fate Stay Night Heaven's Feel release

### ISSUE THREAD

**Issue by zykeeper** [Kaleido-subs/FSN-Heavens-Feel#1]
Fate/Stay Night; Heaven's Feel. I - Presage Flower

50:53 I already raised this in Nyaa comments but better try it here once again;
         can you change "unsalvagable" into "irredeemable"? thanks to Made in Abyss, it leaves an impression to 
         me that whenever i heard "doshigatai" it automatically translate to my head as irredeemable XD

38:58 I still think "Bright-eyes and bushy-tailed now?" is a stretch, so I might as well push my chances here and 
         convince you to change it too. I get it how poeple change wordings when in Gyaru-ish tone or Kansai 
         tone but i think Rin isn't really that sassy. Her tone here is casual and only sounds a little bit annoyed and 
         defeated so I think "Woken up already?" is a good translation for it.

Fate/Stay Night; Heaven's Feel. II - Lost Butterfly

07:14   "Uwah!" idk this just sounds cuter :D
49:12    "I'm Floored"  into "I'm Appalled"

49:20 - 49:36    For a casual Fate watcher who never read or play LN/VN, I prefer Xrip's sub on this because it gives more context about their wish and what does it takes for them to fullfill it. Xrip's subs is something about them choosing/trying to look like humans despite them becoming monsters in pursuit for their original wish. 
(I deleted Xrip's release after having disk space problems but then i realized i never transferred it in HDD and re-downloading would be pointless because SYC releases the trilogy. Hurray!)

Fate/Stay Night; HEaven's Feel. III - Spring Song

00:48 The way Zouken talks sounds weird to me, "acutely aware" can be "perfectly aware", 01:14 the word "druthers" sounds unnatural in a conversation (atleast for me).
					
01:35 "Hey, what does being a big sister is like?"
02:14 "Before, she would merely accept what came to pass regardless of intentions,"
           (change "once" to "before". Also remove the comma between pass and regardless)
02:21 "but you taught her to desire for herself."
02:24 "Now that it had killed so many people, it can no longer be satisfied."
04:47 "That's no good"
16:14 "Emiya Kiritsugu's way of life was beyond my comprehension"
18:15 "It is no doubt that she had preyed on the lives of others"
          (True she had eaten people, but not in a way as wicked and graphic as cannibalism)
18:31 "she has killed far too many people"

I decided to stop checking for subs and enjoy the show when Shiro and Kotomine is going to the castle.

**Comment by LightArrowsEXE** [comment]
Hey, thanks for the Issue. I'll respond to a couple of lines right now and get back to you on the others when I'm free to.

```
50:53 I already raised this in Nyaa comments but better try it here once again;
can you change "unsalvagable" into "irredeemable"? thanks to Made in Abyss, it leaves an impression to
me that whenever i heard "doshigatai" it automatically translate to my head as irredeemable XD
```
Sorry, but just because it was rendered in one way in another movie doesn't mean we'll change it here. "Unsalvagable" is here to stay.

```
38:58 I still think "Bright-eyes and bushy-tailed now?" is a stretch, so I might as well push my chances here and
convince you to change it too. I get it how poeple change wordings when in Gyaru-ish tone or Kansai
tone but i think Rin isn't really that sassy. Her tone here is casual and only sounds a little bit annoyed and
defeated so I think "Woken up already?" is a good translation for it.
```
"Bright-eyed and bushy-tailed" has more bite and is more in line with how we generally handle her character voice. It's not overly "sassy" per se, either. At least not to the extent that I feel like we need to change it.


> 07:14 "Uwah!" idk this just sounds cuter :D

no

> 49:12 "I'm Floored" into "I'm Appalled"

no

```
49:20 - 49:36 For a casual Fate watcher who never read or play LN/VN, I prefer Xrip's sub on this because it gives more context about their wish and what does it takes for them to fullfill it. Xrip's subs is something about them choosing/trying to look like humans despite them becoming monsters in pursuit for their original wish.
```
Will get back to this


> 00:48 The way Zouken talks sounds weird to me, "acutely aware" can be "perfectly aware", 01:14 the word "druthers" sounds unnatural in a conversation (atleast for me).

"Acutely aware" is perfectly fine English, and not particularly uncommon in speech (just tends to be in anime subs because people dumb down lines a lot lol)
["Druthers"](https://www.merriam-webster.com/dictionary/druthers) was chosen on purpose to fit more with Zouken's character voice, which relies more on older constructions and a good old-fashioned lexicon. It's natural in American English (which this script was written in), [but admittedly lesser-known in other parts of the world](https://www.phrases.org.uk/meanings/194850.html). That said, I personally think it's fine and it's easy enough to understand what he's getting at in the line.

> 01:35 "Hey, what does being a big sister is like?"

I have no idea what this line refers to

> 02:14 "Before, she would merely accept what came to pass regardless of intentions,"
> (change "once" to "before". Also remove the comma between pass and regardless)

"Once" is fine, and the comma is there to indicate how the line would be spoken.

> 02:24 "Now that it had killed so many people, it can no longer be satisfied."

["Kinsman"](https://www.merriam-webster.com/dictionary/kinsman) does not mean "many people"

> 04:47 "That's no good"

no

> 18:15 "It is no doubt that she had preyed on the lives of others"
> (True she had eaten people, but not in a way as wicked and graphic as cannibalism)

Disagree. By definition she has cannibalized people, and "preyed on the lives of others" sounds more like he's downplaying it (which he isn't).

> 18:31 "she has killed far too many people"

"A great many" is perfectly fine English.

**Comment by petzku** [comment]
I'll share my thoughts as well:

### 02

> 49:20 - 49:36 For a casual Fate watcher who never read or play LN/VN, I prefer Xrip's sub on this because it gives more context about their wish and what does it takes for them to fullfill it. Xrip's subs is something about them choosing/trying to look like humans despite them becoming monsters in pursuit for their original wish.

I don't see much need to change this. The lines in question, as best I can tell:
```
Remember again what we earnestly wished for.
Remember where our thirst for achieving the miracle came from.
And why we've been striving to reach the point where we're not human...
while keeping our human bodies.
```
The dialogue in that scene *could* probably use some love, but overall I much prefer ours to Aniplex's (which is what Xrip uses). Will check with TL on the "keeping our human bodies" aspect, but overall it seems like a very minor thing and might be hard to implement while remaining otherwise natural and fluid.

### 03

> 01:35 "Hey, what does being a big sister is like?"

This line seems like it could be interpreted either way. Checking with the translator.

>  02:21 "but you taught her to desire for herself."

IIRC I suggested this previously, but the current line is more TL-accurate.

>  16:14 "Emiya Kiritsugu's way of life was beyond my comprehension"

The line could be better, but the meaning in ours is correct.
Possibly something like "I was utterly incompatible with his way of life."

**Comment by zykeeper** [comment]
> 01:35 "Hey, what does being a big sister is like?"

I rememebered watching it in youtube. The title is "Finding Heroes in Fate/stay night: Heaven's Feel III. spring song" by Under The Scope, around 4:08 mark of the video. Illya ask Rin what it's like to be the Older sister but then Rin responds with a silent treatment.

**Comment by zykeeper** [comment]
> > 04:47 "That's no good"
> 
> no

Sorry wrong timestamp. I think the line "That's no good" fits more in line with the next sentences than "now,now"
04:38 "That's no good" 
04:43 "If you use that kind of magecraft,"
04:46 "you'll bring the whole house down."

**Comment by LightArrowsEXE** [comment]
I figured that was what you meant, so my "no" still stands.

**Comment by petzku** [comment]
> Sorry wrong timestamp. I think the line "That's no good" fits more in line with the next sentences than "now,now"

To elaborate a bit: "now, now" has a much more playful tone, which fits Sakura well in this scene (she clearly outpowers Rin and is just toying with her). In a vacuum, it might be too mild a reprimand, but here it works perfectly.

**Comment by zykeeper** [comment]
> > Sorry wrong timestamp. I think the line "That's no good" fits more in line with the next sentences than "now,now"
> 
> To elaborate a bit: "now, now" has a much more playful tone, which fits Sakura well in this scene (she clearly outpowers Rin and is just toying with her). In a vacuum, it might be too mild a reprimand, but here it works perfectly.

Oh I see, sorry I think I'm just not used in this way of fansubbing

**Comment by LightArrowsEXE** [comment]
> Oh I see, sorry I think I'm just not used in this way of fansubbing

These are standard translation/editing practices, though 🤔. Just because most fansubbers are prone to simple word substitution and minor grammatical fixes doesn't mean that's how you do translation. You take the overall work into account, how characters are likely to come across in general, what the readers are supposed to interpret, and rewrite it in a way that makes sense to the target audience (in our case, this is always a native English audience who might not necessarily be used to anime, but still wants to be able to enjoy it without odd phrasing that ESLs have grown used to bogging it down for them).

**Comment by petzku** [comment]
After some discussion with TLC and ED, we decided the lines we have are fine (possible, though not the *only* interpretations), so I'm closing this.
